version: "3.8"

services:
  python:
    build:
      context: .
      dockerfile: Dockerfile.python
    ports:
      - "8000:8000"
    env_file:
      - .env

  node:
    platform: linux/arm64
    #devices:
      #- "/dev/snd:/dev/snd"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - python
