services:
  python:
    build:
      context: .
      dockerfile: Dockerfile.python
    ports:
      - "8000:8000"
    env_file:
      - .env

  node:
    platform: linux/arm64
    devices:
      - "/dev/snd:/dev/snd"
    volumes:
       - /run/user/1000/pulse/native:/run/user/1000/pulse/native
    environment:
       - PULSE_SERVER=unix:/run/user/1000/pulse/native
       - DEBUG=record 
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - python